"use strict";
exports.__esModule = true;
var express_1 = require("express");
var index_controller_1 = require("../controllers/index.controller");
var router = express_1.Router();
router.get("/users", index_controller_1.getUsers);
router.get("/users/:id", index_controller_1.getUserByID);
router.post("/users", index_controller_1.createUser);
router["delete"]("/users/:id", index_controller_1.deleteUser);
router.put("/users/:id", index_controller_1.updateUser);
exports["default"] = router;
